name: Verify

on:
  push:
    branches: ['**']
  pull_request:

permissions:
  contents: read

concurrency:
  group: verify-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.11.1 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm 9.6.0
        run: corepack prepare pnpm@9.6.0 --activate

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Verify (types + lint + build + formatcheck)
        run: pnpm verify
